### ISSUE TITLE
what diffusers version this repo use?

### ISSUE THREAD

**Issue by lizekui** [TkskKurumi/DiffusersFastAPI#1]
Hi dear TkskKurumi, your repo is so fantastic.
I wonder what diffusers version this repo use? can you share it? I use newest version of it, but met some version confilict

**Comment by TkskKurumi** [comment]
Which ever supports StableDiffusionPipeline.from_pretrained.
I've also encountered dependency issues when installing diffusers with pypi, so I cloned its github repository and manually installed it.

**Comment by TkskKurumi** [comment]
Hi, I've added dependencies installation script, it may work fine.
Torch is not included in the script since likely you may choose your suitable cuda version to install.

**Comment by lizekui** [comment]
Thanks！
